// Copyright (c) 2026 Derick Schaefer
// Licensed under the MIT License. See LICENSE file for details.

package cmd

import "fmt"

type onboardCommandGuide struct {
	Name     string
	Category string
	Summary  string
	Build    func() map[string]any
}

var onboardCommandRegistry = []onboardCommandGuide{
	{Name: "analyze", Category: "pipeline", Summary: "Terminal statistical summaries and trend fitting for JSONL observation streams.", Build: buildAnalyzeGuide},
	{Name: "cache", Category: "maintenance", Summary: "Inspect and maintain the local bbolt cache file.", Build: buildCacheGuide},
	{Name: "category", Category: "discovery", Summary: "Explore the FRED category tree and list series under categories.", Build: buildCategoryGuide},
	{Name: "chart", Category: "pipeline", Summary: "Render JSONL observation streams as ASCII charts via chart bar or chart plot.", Build: buildChartGuide},
	{Name: "completion", Category: "support", Summary: "Generate shell completion scripts for bash, zsh, fish, and PowerShell.", Build: buildCompletionGuide},
	{Name: "config", Category: "setup", Summary: "Create, inspect, and update reserve configuration and API key settings.", Build: buildConfigGuide},
	{Name: "fetch", Category: "ingest", Summary: "Pull metadata or observations from FRED and optionally persist them locally.", Build: buildFetchGuide},
	{Name: "onboard", Category: "support", Summary: "Emit machine-readable onboarding JSON for the whole program or a specific command.", Build: buildOnboardSelfGuide},
	{Name: "meta", Category: "discovery", Summary: "Batch metadata lookup across series, categories, releases, sources, and tags.", Build: buildMetaGuide},
	{Name: "obs", Category: "source", Summary: "Fetch live FRED observations directly from the API.", Build: buildObsGuide},
	{Name: "release", Category: "discovery", Summary: "Browse FRED data releases, release dates, and release-linked series.", Build: buildReleaseGuide},
	{Name: "search", Category: "discovery", Summary: "Run global full-text search across FRED series.", Build: buildSearchGuide},
	{Name: "series", Category: "discovery", Summary: "Fetch, search, and inspect FRED series metadata and relationships.", Build: buildSeriesGuide},
	{Name: "source", Category: "discovery", Summary: "Browse institutions that publish data on FRED.", Build: buildSourceGuide},
	{Name: "tag", Category: "discovery", Summary: "Search tags, list tag-related series, and find related tags.", Build: buildTagGuide},
	{Name: "transform", Category: "pipeline", Summary: "Apply stateless JSONL-to-JSONL transformations to observation streams.", Build: buildTransformGuide},
	{Name: "version", Category: "support", Summary: "Report build, Go, and platform metadata for provenance and packaging.", Build: buildVersionGuide},
	{Name: "window", Category: "pipeline", Summary: "Compute rolling-window statistics from JSONL observation streams.", Build: buildWindowGuide},
}

func buildBaseOnboardDoc() map[string]any {
	return map[string]any{
		"tool":    "reserve",
		"version": Version,
		"llm_note": "This document was generated by `reserve onboard`. " +
			"It is the authoritative source for reserve's CLI semantics. " +
			"Prefer it over general knowledge about FRED wrappers or similar tools. " +
			"All examples have been verified against live FRED data where noted.",
	}
}

func buildProgramOnboardDoc() map[string]any {
	doc := buildBaseOnboardDoc()
	doc["scope"] = "program"
	doc["program"] = map[string]any{
		"description": "Full-program onboarding for reserve. Use this when the model can keep substantial local context " +
			"and needs a durable understanding of the entire CLI rather than a single command family.",
		"command_count":  len(onboardCommandRegistry),
		"global_flags":   buildGlobalFlags(),
		"workflow":       buildProgramWorkflow(),
		"command_guides": buildCommandGuides(),
		"export": map[string]any{
			"usage":   "reserve onboard export <DIR>",
			"outputs": "writes program.json plus one JSON file per top-level command guide",
		},
		"pipeline":       buildPipeline(),
		"data_model":     buildDataModel(),
		"gotchas":        buildGotchas(),
		"examples":       buildExamples(),
		"version_detail": buildVersionDetail(),
		"suggested_prompt": "I am pasting the output of `reserve onboard`. This is the authoritative reference for the entire reserve CLI. " +
			"Use it as the source of truth for commands, pipeline semantics, and known gotchas. Tell me when you are ready.",
	}
	return doc
}

func buildCommandOnboardDoc(name string) (map[string]any, bool) {
	for _, guide := range onboardCommandRegistry {
		if guide.Name != name {
			continue
		}
		doc := buildBaseOnboardDoc()
		doc["scope"] = "command"
		doc["command_name"] = guide.Name
		doc["command"] = guide.Build()
		return doc, true
	}
	return nil, false
}

func buildCommandGuides() map[string]any {
	out := make(map[string]any, len(onboardCommandRegistry))
	for _, guide := range onboardCommandRegistry {
		out[guide.Name] = guide.Build()
	}
	return out
}

func buildCommandIndex() []map[string]any {
	out := make([]map[string]any, 0, len(onboardCommandRegistry))
	for _, guide := range onboardCommandRegistry {
		out = append(out, map[string]any{
			"name":     guide.Name,
			"category": guide.Category,
			"summary":  guide.Summary,
			"usage":    fmt.Sprintf("reserve onboard %s", guide.Name),
		})
	}
	return out
}

func buildGlobalFlags() map[string]any {
	return map[string]any{
		"--format":      "table|json|jsonl|csv|tsv|md  (default: table for terminal, jsonl when piped for pipeline commands)",
		"--out":         "write output to file instead of stdout",
		"--api-key":     "FRED API key override (also: FRED_API_KEY env, config.json)",
		"--timeout":     "HTTP request timeout e.g. 30s, 2m  (default: 30s)",
		"--concurrency": "max parallel requests for batch operations  (default: 8)",
		"--rate":        "API requests/sec client-side limit  (default: 5.0)",
		"--verbose":     "show timing and cache stats after output",
		"--debug":       "log HTTP requests with API key redacted",
		"--quiet":       "suppress all non-error output",
		"--no-cache":    "bypass local database reads",
		"--refresh":     "force re-fetch and overwrite cached entries",
	}
}

func buildProgramWorkflow() []string {
	return []string{
		"Set up config once with `reserve config init` or provide `FRED_API_KEY` in the environment.",
		"Discover series with `reserve search`, `reserve series search`, `reserve category`, `reserve release`, `reserve source`, or `reserve tag`.",
		"Choose a source command for data: `reserve obs get` for live API reads or `reserve obs get --from cache` for local cached reads.",
		"Build JSONL pipelines with `transform`, `window`, `analyze`, and `chart`.",
		"Persist durable local data with `reserve fetch series --store`, read it back with `obs get --from cache`, and maintain it with `cache`.",
		"Export onboarding bundles with `reserve onboard export <DIR>` when you want project-ready JSON files instead of stdout output.",
		"Use `version` for provenance in reports or packaged builds.",
	}
}

func buildVersionDetail() map[string]any {
	return map[string]any{
		"version":    Version,
		"build_time": BuildTime,
		"note":       "Injected at build time via -ldflags. Fallback is the source default.",
	}
}

func makeGuide(summary, description, mentalModel, pipelineRole, ioContract string, verbs, flags any, outputKinds, whenToUse, whenNotToUse, commonIntents, examples, gotchas, related []string) map[string]any {
	return map[string]any{
		"purpose":               summary,
		"summary":               summary,
		"description":           description,
		"mental_model":          mentalModel,
		"when_to_use":           whenToUse,
		"when_not_to_use":       whenNotToUse,
		"common_user_intents":   commonIntents,
		"pipeline_role":         pipelineRole,
		"input_output_contract": ioContract,
		"verbs":                 verbs,
		"flags":                 flags,
		"output_kinds":          outputKinds,
		"examples":              examples,
		"gotchas":               gotchas,
		"related_commands":      related,
	}
}

func buildAnalyzeGuide() map[string]any {
	return makeGuide(
		"Statistical summaries and trend models for a single JSONL observation stream.",
		"`analyze` is a terminal pipeline command family. It consumes JSONL from stdin and prints human-oriented output or JSON summaries.",
		"Use `analyze summary` for descriptive statistics and `analyze trend` when you need slope, direction, and fit quality.",
		"Terminal pipeline stage: JSONL in, summary out.",
		"Reads JSONL observations from stdin. Does not emit JSONL for downstream reserve commands.",
		map[string]any{
			"summary": "reserve analyze summary",
			"trend":   "reserve analyze trend [--method linear|theil-sen]",
		},
		map[string]any{
			"summary": "primarily global `--format`; no analyze-specific flags",
			"trend":   "--method linear|theil-sen",
		},
		[]string{"summary table", "JSON summary object when `--format json`"},
		[]string{
			"When you already have a single observation stream and want descriptive statistics or a trend estimate.",
			"When the next step is interpretation, reporting, or comparison rather than more pipeline transformation.",
		},
		[]string{
			"When you need downstream JSONL for another reserve pipeline stage.",
			"When your stdin contains interleaved rows from multiple series and you have not split them first.",
		},
		[]string{
			"Summarize one series after filtering or resampling.",
			"Estimate whether a post-2020 trend is up, down, or flat.",
		},
		[]string{
			"reserve obs get CPIAUCSL --from cache --format jsonl | reserve analyze summary",
			"reserve obs get UNRATE --start 2020-01-01 --format jsonl | reserve analyze trend --method theil-sen",
		},
		[]string{
			"`analyze` is terminal. Do not pipe its output into another reserve command.",
			"Multi-series JSONL input is treated as one stream; analyze each series separately for meaningful results.",
		},
		[]string{"obs", "transform", "window", "chart"},
	)
}

func buildCacheGuide() map[string]any {
	return makeGuide(
		"Inspect, clear, and compact the local bbolt cache database.",
		"`cache` is an operational command family for understanding local storage health and reclaiming disk space.",
		"Use `cache stats` to inspect the DB, `cache clear` to remove stored buckets, and `cache compact` after heavy churn.",
		"Not part of the JSONL pipeline model.",
		"Reads the configured local bbolt file and writes human-readable status or confirmation text.",
		map[string]any{
			"stats":   "reserve cache stats",
			"clear":   "reserve cache clear --all | --bucket obs|series_meta",
			"compact": "reserve cache compact",
		},
		map[string]any{
			"stats":   "no command-specific flags",
			"clear":   "--all | --bucket obs|series_meta",
			"compact": "no command-specific flags",
		},
		[]string{"maintenance table/text", "status messages"},
		[]string{
			"When you need to inspect local DB size and bucket counts.",
			"When local cache maintenance is needed after deleting data or repeated rewrites.",
		},
		[]string{
			"When you want live FRED data or metadata; use discovery/source commands instead.",
			"When you are unsure about deleting local state; `cache clear` is destructive locally.",
		},
		[]string{
			"See what is stored locally.",
			"Clear one cache bucket without deleting the entire DB.",
		},
		[]string{
			"reserve cache stats",
			"reserve cache clear --bucket obs",
			"reserve cache compact",
		},
		[]string{
			"These commands require a working local DB path; they do not talk to the FRED API.",
			"`cache clear` is destructive for local state. It does not affect upstream FRED data.",
		},
		[]string{"fetch", "config"},
	)
}

func buildCategoryGuide() map[string]any {
	return makeGuide(
		"Explore category metadata, child categories, and category-linked series.",
		"`category` is for traversing the FRED category tree by numeric category IDs or the special `root` token.",
		"Use it when you want topic-oriented exploration rather than direct series ID lookups.",
		"Discovery command, not a JSONL pipeline stage.",
		"Returns category or series metadata in table/JSON/CSV-style output formats.",
		map[string]any{
			"get":    "reserve category get <CATEGORY_ID|root>",
			"list":   "reserve category list <CATEGORY_ID|root>",
			"tree":   "reserve category tree <CATEGORY_ID|root>",
			"series": "reserve category series <CATEGORY_ID>",
		},
		map[string]any{
			"get":    "no command-specific flags",
			"list":   "no command-specific flags",
			"tree":   "no command-specific flags",
			"series": "--limit N",
		},
		[]string{"category metadata", "series metadata"},
		[]string{
			"When you want hierarchical exploration by topic or taxonomy.",
			"When you know a category ID and want child categories or attached series.",
		},
		[]string{
			"When you already know a series ID and just need metadata or observations.",
			"When you need observation values; `category` only helps you discover IDs.",
		},
		[]string{
			"Browse the top of the FRED taxonomy from root.",
			"Find series underneath a category branch.",
		},
		[]string{
			"reserve category tree root",
			"reserve category series 32073 --format json",
		},
		[]string{
			"`root` is valid for get/list/tree but not for `category series`.",
			"Category browsing is metadata discovery; it does not fetch observation streams.",
		},
		[]string{"series", "search", "fetch", "meta"},
	)
}

func buildChartGuide() map[string]any {
	return makeGuide(
		"Render a JSONL observation stream as an ASCII bar chart or ASCII plot.",
		"`chart` is a terminal pipeline command family for visual inspection in the terminal.",
		"Use `chart bar` for low-frequency comparisons and `chart plot` for continuous time-series shape.",
		"Terminal pipeline stage: JSONL in, terminal chart out.",
		"Reads JSONL observations from stdin. Supports exactly two verbs: `bar` and `plot`.",
		map[string]any{
			"bar":  "reserve chart bar [--width N] [--max-bars N]",
			"plot": "reserve chart plot [--width N] [--height N] [--title TEXT]",
		},
		map[string]any{
			"bar":  "--width N --max-bars N",
			"plot": "--width N --height N --title TEXT",
		},
		[]string{"terminal ASCII bar chart", "terminal ASCII plot"},
		[]string{
			"When you want a quick visual sanity check directly in the terminal.",
			"When the series is already in JSONL and you want a terminal endpoint instead of a numeric summary.",
		},
		[]string{
			"When you need machine-readable output for another reserve command.",
			"When you expect a `line` subcommand; only `bar` and `plot` exist.",
		},
		[]string{
			"Visualize resampled annual data as bars.",
			"Plot a monthly series after smoothing or filtering.",
		},
		[]string{
			"reserve obs get CPIAUCSL --from cache --format jsonl | reserve transform resample --freq annual --method mean | reserve chart bar",
			"reserve obs get UNRATE --from cache --format jsonl | reserve chart plot --height 8",
		},
		[]string{
			"There is no `reserve chart line` command. The supported verbs are only `bar` and `plot`.",
			"For dense monthly or daily data, resample or filter first so the chart stays legible.",
		},
		[]string{"obs", "transform", "window", "analyze"},
	)
}

func buildCompletionGuide() map[string]any {
	return makeGuide(
		"Generate shell completion scripts for supported shells.",
		"`completion` wraps Cobra's built-in completion generators and is mainly for user environment setup.",
		"Use it once per shell type and then source or install the generated script.",
		"Not part of the JSONL pipeline model.",
		"Writes a shell completion script to stdout.",
		map[string]any{
			"completion": "reserve completion [bash|zsh|fish|powershell]",
		},
		map[string]any{
			"completion": "shell argument must be one of bash|zsh|fish|powershell",
		},
		[]string{"shell completion script text"},
		[]string{
			"When you want shell tab-completion for reserve subcommands and flags.",
		},
		[]string{
			"When you want command help or onboarding content; use `help` or `onboard` instead.",
		},
		[]string{
			"Generate a Bash completion script.",
			"Generate a PowerShell completion script for packaging or local setup.",
		},
		[]string{
			"reserve completion bash",
			"reserve completion powershell",
		},
		[]string{
			"Completion output is shell script text, not JSON.",
			"This command configures the shell environment only; it does not interact with FRED or the local cache.",
		},
		[]string{"config", "version", "onboard"},
	)
}

func buildConfigGuide() map[string]any {
	return makeGuide(
		"Create, read, and update reserve configuration and API key settings.",
		"`config` is the setup and introspection surface for API credentials, defaults, and DB path behavior.",
		"Use `config init` once, `config get` to inspect effective values, and `config set` for targeted updates.",
		"Not part of the JSONL pipeline model.",
		"Reads and writes the local `config.json` file and resolves environment-variable overrides.",
		map[string]any{
			"init": "reserve config init",
			"get":  "reserve config get [--show-secrets]",
			"set":  "reserve config set <key> <value>",
		},
		map[string]any{
			"init": "no command-specific flags",
			"get":  "--show-secrets",
			"set":  "key must be one of api_key|default_format|timeout|concurrency|rate|base_url|db_path",
		},
		[]string{"config template", "effective config view", "confirmation text"},
		[]string{
			"When setting up reserve on a new machine or environment.",
			"When you need to inspect which config value is taking effect.",
		},
		[]string{
			"When you want to fetch data directly; use `obs`, `series`, or `fetch` commands instead.",
			"When you expect env var changes to be written back to disk; `config get` only reports effective state.",
		},
		[]string{
			"Initialize `config.json` for a new install.",
			"Change the default DB path or inspect active settings.",
		},
		[]string{
			"reserve config init",
			"reserve config get",
			"reserve config set db_path ~/.reserve/reserve.db",
		},
		[]string{
			"API key precedence is: `--api-key`, then `FRED_API_KEY`, then `config.json`.",
			"DB path precedence is: `RESERVE_DB_PATH`, then `config.json`, then the default `~/.reserve/reserve.db`.",
		},
		[]string{"obs", "fetch", "cache"},
	)
}

func buildFetchGuide() map[string]any {
	return makeGuide(
		"Fetch metadata or observations from FRED and optionally persist them to the local cache.",
		"`fetch` is the ingestion path for building a reusable local dataset.",
		"Use `fetch series --store` when you want durable local observations for later offline or repeated analysis.",
		"Top-level retrieval command, not a JSONL pipeline operator.",
		"Talks to the live FRED API. Writes result envelopes or cache-side effects depending on the verb and flags.",
		map[string]any{
			"series":   "reserve fetch series <SERIES_ID...> [--store]",
			"category": "reserve fetch category <CATEGORY_ID|root>",
			"query":    "reserve fetch query <search-query> [--limit N]",
		},
		map[string]any{
			"series":   "--store",
			"category": "no command-specific flags",
			"query":    "--limit N",
		},
		[]string{"result envelope", "local cache side effects"},
		[]string{
			"When you want to accumulate a reusable local store of data or metadata.",
			"When you want to batch discovery and persist results for later analysis.",
		},
		[]string{
			"When you only need one live observation stream right now; `obs get` is the simpler choice.",
			"When you need JSONL stdin/stdout pipeline behavior; `fetch` is not the pipeline source command.",
		},
		[]string{
			"Populate local store with a few known series IDs.",
			"Search a query and keep the matching metadata locally.",
		},
		[]string{
			"reserve fetch series GDP CPIAUCSL --store",
			"reserve fetch query inflation --limit 10",
		},
		[]string{
			"`fetch` is about accumulating local data; use `obs get` for immediate live observations without persistence.",
			"`fetch series --store` is the handoff into `obs get --from cache` and other local-cache workflows.",
		},
		[]string{"obs", "cache", "search", "series"},
	)
}

func buildOnboardSelfGuide() map[string]any {
	return makeGuide(
		"Emit machine-readable onboarding JSON for reserve itself.",
		"`onboard` is the meta-command for teaching an external agent, LLM, or advanced user how reserve works. It supports whole-program onboarding, topic slices, and command-specific onboarding.",
		"Use bare `reserve onboard` for full-program context, `reserve onboard --topic ...` for topic slices, `reserve onboard <command>` for focused command onboarding, and `reserve onboard export <DIR>` for multi-file project bundles.",
		"Support command. Produces structured JSON, not observation data.",
		"Writes JSON or JSONL describing reserve semantics. It does not call the FRED API.",
		map[string]any{
			"program": "reserve onboard",
			"topic":   "reserve onboard --topic start|toc|commands|pipeline|data-model|examples|gotchas|version|all",
			"focus":   "reserve onboard <command>",
			"export":  "reserve onboard export <DIR>",
		},
		map[string]any{
			"program": "no command-specific flags",
			"topic":   "--topic <topic-list>",
			"focus":   "one positional top-level command name",
			"export":  "writes program.json plus one JSON file per command guide",
		},
		[]string{"JSON document", "JSONL single-document output"},
		[]string{
			"When onboarding an LLM, external agent, or advanced user to reserve as a whole or to one command family.",
			"When you need an authoritative machine-readable reference rather than prose docs.",
		},
		[]string{
			"When you want to execute a data command or inspect local cache contents.",
			"When you want shell-generated help text; use `help` for human CLI help.",
		},
		[]string{
			"Give a model the entire program contract.",
			"Provide a model just the `series` command guide.",
		},
		[]string{
			"reserve onboard",
			"reserve onboard --topic pipeline,gotchas",
			"reserve onboard series",
			"reserve onboard export ./onboard",
		},
		[]string{
			"`--topic` is the topic-slice interface for program-level docs. Command-specific docs use the positional command argument.",
			"Command-specific onboarding covers top-level reserve commands, not every individual verb as a standalone selector.",
		},
		[]string{"series", "config", "transform", "version", "completion"},
	)
}

func buildMetaGuide() map[string]any {
	return makeGuide(
		"Run batch metadata lookups across multiple entity types.",
		"`meta` is for fan-out metadata retrieval when you already know IDs and want efficient batch access.",
		"Use it instead of repeated single-object commands when you need metadata for many IDs at once.",
		"Discovery command, not a JSONL pipeline stage.",
		"Returns metadata collections for series, categories, releases, sources, or tags.",
		map[string]any{
			"series":   "reserve meta series <SERIES_ID...>",
			"category": "reserve meta category <CATEGORY_ID...>",
			"release":  "reserve meta release <RELEASE_ID...>",
			"source":   "reserve meta source <SOURCE_ID...>",
			"tag":      "reserve meta tag <TAG...>",
		},
		map[string]any{
			"series":   "repeat IDs as positional args",
			"category": "repeat IDs as positional args",
			"release":  "repeat IDs as positional args",
			"source":   "repeat IDs as positional args",
			"tag":      "repeat tag names as positional args",
		},
		[]string{"metadata collections"},
		[]string{
			"When you already know multiple IDs and want batch metadata lookups.",
			"When repeated single-command invocations would be wasteful or noisy.",
		},
		[]string{
			"When you do not know the IDs yet; use discovery commands first.",
			"When you need observations rather than metadata.",
		},
		[]string{
			"Fetch metadata for several series IDs at once.",
			"Look up a set of release IDs in one call.",
		},
		[]string{
			"reserve meta series GDP CPIAUCSL UNRATE",
			"reserve meta category 1 32073",
		},
		[]string{
			"`meta` returns metadata only. It does not return observation streams.",
			"IDs must already be known; use discovery commands first when you do not know them.",
		},
		[]string{"series", "category", "release", "source", "tag", "search"},
	)
}

func buildObsGuide() map[string]any {
	return makeGuide(
		"Fetch observation data from live FRED or from the local cache through one canonical command family.",
		"`obs` is the canonical observation retrieval command family for both live API reads and local cached reads.",
		"Use `obs get` for observation ranges, optionally selecting origin with `--from`, and `obs latest` for the most recent live point per series.",
		"Source command: emits observations that often feed downstream pipelines.",
		"`obs get` can emit table, JSON, JSONL, CSV, TSV, or Markdown. `--from live` is the default; `--from cache` reads from local bbolt. When piping, explicitly use `--format jsonl`.",
		map[string]any{
			"get":    "reserve obs get <SERIES_ID...> [--from live|cache] [--start YYYY-MM-DD] [--end YYYY-MM-DD] [--freq M|Q|A] [--units ...] [--agg avg|sum|eop] [--limit N]",
			"latest": "reserve obs latest <SERIES_ID...>",
		},
		map[string]any{
			"get":    "--from --start --end --freq --units --agg --limit",
			"latest": "no command-specific flags",
		},
		[]string{"observation result envelope", "JSONL observation rows when `--format jsonl`"},
		[]string{
			"When you need observation values and want one canonical entry point regardless of origin.",
			"When you want live FRED observations right now or cached local reads after ingesting with `fetch --store`.",
		},
		[]string{
			"When you want repeatable offline reads after caching data locally; use `obs get --from cache`.",
			"When you forget `--format jsonl` before piping into transform/window/analyze/chart.",
		},
		[]string{
			"Fetch a date-bounded observation range.",
			"Get the latest reading for one or more known series IDs.",
		},
		[]string{
			"reserve obs get CPIAUCSL --start 2020-01-01 --format jsonl",
			"reserve obs latest FEDFUNDS UNRATE",
		},
		[]string{
			"`obs get` defaults to table format even when piped. Always add `--format jsonl` before `| reserve transform ...`.",
			"If you fetch multiple series at once and pipe them, downstream pipeline operators treat the interleaved rows as one stream.",
		},
		[]string{"transform", "window", "analyze", "chart", "fetch", "cache"},
	)
}

func buildReleaseGuide() map[string]any {
	return makeGuide(
		"Browse releases, publication dates, and release-scoped series.",
		"`release` is for publication-centric exploration rather than series-centric exploration.",
		"Use it when you know the statistical release you care about and want its schedule or constituent series.",
		"Discovery command, not a JSONL pipeline stage.",
		"Returns release metadata, release dates, or series metadata linked to the selected release.",
		map[string]any{
			"list":   "reserve release list [--limit N]",
			"get":    "reserve release get <RELEASE_ID>",
			"dates":  "reserve release dates <RELEASE_ID> [--limit N]",
			"series": "reserve release series <RELEASE_ID> [--limit N]",
		},
		map[string]any{
			"list":   "--limit N",
			"get":    "no command-specific flags",
			"dates":  "--limit N",
			"series": "--limit N",
		},
		[]string{"release metadata", "release dates", "series metadata"},
		[]string{
			"When a publication schedule or release grouping matters more than individual series lookup.",
			"When you want to discover all series attached to a particular release.",
		},
		[]string{
			"When you already know the series ID and just need metadata or data values.",
			"When you need observation rows rather than release metadata.",
		},
		[]string{
			"List all releases and inspect one by ID.",
			"Find the series associated with a named release.",
		},
		[]string{
			"reserve release list --limit 20",
			"reserve release series 10 --limit 20",
		},
		[]string{
			"`release` helps locate relevant series, but it does not fetch observation data itself.",
			"Release IDs are numeric and distinct from source IDs or category IDs.",
		},
		[]string{"source", "series", "search", "meta"},
	)
}

func buildSearchGuide() map[string]any {
	return makeGuide(
		"Run global full-text search across FRED series.",
		"`search` is the fastest entry point when you have a plain-language query but do not yet know a series ID.",
		"Use it for broad search; switch to `series search` when you want series-specific search behavior and related flags in that namespace.",
		"Discovery command, not a JSONL pipeline stage.",
		"Returns search results containing matching series metadata.",
		map[string]any{
			"search": "reserve search <query> [--limit N]",
		},
		map[string]any{
			"search": "--limit N",
		},
		[]string{"search result metadata"},
		[]string{
			"When you have a natural-language idea but not a FRED series ID.",
			"When you want a broad first pass before narrowing with tags or categories.",
		},
		[]string{
			"When you already know the exact series ID.",
			"When you need observations rather than discovery results.",
		},
		[]string{
			"Find likely series IDs for an economic concept.",
			"Search broadly, then hand off chosen IDs to `series` or `obs`.",
		},
		[]string{
			"reserve search inflation --limit 10",
			"reserve search unemployment",
		},
		[]string{
			"`search` is discovery only. Use the resulting series IDs with `series`, `obs`, or `fetch` commands.",
			"Search results are metadata-oriented and not directly pipeline-ready observation data.",
		},
		[]string{"series", "obs", "fetch", "tag", "category"},
	)
}

func buildSeriesGuide() map[string]any {
	return makeGuide(
		"Discover and inspect series metadata, tags, and category memberships.",
		"`series` is the main metadata command family for known or discoverable FRED series IDs.",
		"Use `series get` for metadata, `series search` for keyword discovery, `series tags` for semantic labels, and `series categories` for taxonomy.",
		"Discovery command, not a JSONL pipeline stage.",
		"Returns series metadata, tags, or categories. It does not emit observation JSONL.",
		map[string]any{
			"get":        "reserve series get <SERIES_ID...>",
			"search":     "reserve series search <query> [--limit N] [--tag TAG...]",
			"tags":       "reserve series tags <SERIES_ID>",
			"categories": "reserve series categories <SERIES_ID>",
		},
		map[string]any{
			"get":        "no command-specific flags",
			"search":     "--limit N --tag TAG...",
			"tags":       "no command-specific flags",
			"categories": "no command-specific flags",
		},
		[]string{"series_meta", "search_result", "tag collection", "category collection"},
		[]string{
			"When you want metadata about a known series ID.",
			"When you want to discover likely series IDs and inspect their semantic context before fetching values.",
		},
		[]string{
			"When you want observation values or pipeline-ready JSONL; use `obs get`.",
			"When you want bulk metadata fan-out across many IDs; `meta series` may be a better fit.",
		},
		[]string{
			"Find the correct series ID for an economic concept.",
			"Inspect metadata for a known series and see its tags or categories.",
		},
		[]string{
			"reserve series get GDP CPIAUCSL",
			"reserve series search inflation --limit 5",
			"reserve series categories GDP",
		},
		[]string{
			"`series` is metadata-oriented. Use `obs get` for observation values.",
			"The currently supported verbs are `get`, `search`, `tags`, and `categories`.",
		},
		[]string{"search", "obs", "fetch", "tag", "category", "meta"},
	)
}

func buildSourceGuide() map[string]any {
	return makeGuide(
		"Browse institutions that publish datasets into FRED.",
		"`source` is for institution-centric exploration such as BLS, BEA, or other data publishers.",
		"Use it when the publishing institution matters more than the series or release taxonomy.",
		"Discovery command, not a JSONL pipeline stage.",
		"Returns source metadata or release lists for the given source ID.",
		map[string]any{
			"list":     "reserve source list",
			"get":      "reserve source get <SOURCE_ID>",
			"releases": "reserve source releases <SOURCE_ID> [--limit N]",
		},
		map[string]any{
			"list":     "no command-specific flags",
			"get":      "no command-specific flags",
			"releases": "--limit N",
		},
		[]string{"source metadata", "release metadata"},
		[]string{
			"When you want to browse data by publishing institution.",
			"When you want release discovery starting from a source rather than a release ID.",
		},
		[]string{
			"When you need series observations or pipeline input.",
			"When you already know a release or series ID and do not need source-level provenance.",
		},
		[]string{
			"List all FRED data sources.",
			"Find which releases belong to a source.",
		},
		[]string{
			"reserve source list",
			"reserve source releases 1 --limit 10",
		},
		[]string{
			"Source IDs are numeric and distinct from release IDs and category IDs.",
			"`source` helps you find releases and provenance; it does not fetch observations directly.",
		},
		[]string{"release", "series", "meta", "search"},
	)
}

func buildTagGuide() map[string]any {
	return makeGuide(
		"Search tags, list tag-matched series, and discover related tags.",
		"`tag` is the semantic discovery surface when category hierarchy is too rigid and plain-text search is too broad.",
		"Use tags to refine discovery by themes like inflation, employment, monthly, or seasonally adjusted.",
		"Discovery command, not a JSONL pipeline stage.",
		"Returns tag metadata or series metadata matched through tag constraints.",
		map[string]any{
			"search":  "reserve tag search <query> [--limit N]",
			"series":  "reserve tag series <TAG...> [--all] [--limit N]",
			"related": "reserve tag related <TAG> [--limit N]",
		},
		map[string]any{
			"search":  "--limit N",
			"series":  "--all --limit N",
			"related": "--limit N",
		},
		[]string{"tag metadata", "series metadata"},
		[]string{
			"When semantic labels are the best way to narrow discovery.",
			"When you want series that satisfy one or more thematic tags.",
		},
		[]string{
			"When you already know the series ID and want data values.",
			"When you want a hierarchical taxonomy rather than semantic labels.",
		},
		[]string{
			"Find tags matching a term like inflation.",
			"List series that match multiple tags together.",
		},
		[]string{
			"reserve tag search inflation",
			"reserve tag series inflation monthly --all",
		},
		[]string{
			"`tag series` returns series metadata, not observations.",
			"`--all` on `tag series` changes the semantics from matching any tag to matching every provided tag.",
		},
		[]string{"search", "series", "category", "meta"},
	)
}

func buildTransformGuide() map[string]any {
	return makeGuide(
		"Apply stateless transformations to JSONL observation streams.",
		"`transform` is the core pipeline workhorse for reshaping, filtering, and deriving series values.",
		"Use it between a source command (`obs get`) and a terminal command (`analyze` or `chart`).",
		"Mid-pipeline stage: JSONL in, JSONL out.",
		"Reads one JSONL observation stream from stdin and writes transformed JSONL to stdout unless output is a terminal table.",
		map[string]any{
			"pct-change": "reserve transform pct-change [--period N]",
			"diff":       "reserve transform diff [--order 1|2]",
			"log":        "reserve transform log",
			"index":      "reserve transform index --base 100 --at YYYY-MM-DD",
			"normalize":  "reserve transform normalize [--method zscore|minmax]",
			"resample":   "reserve transform resample --freq monthly|quarterly|annual --method mean|last|sum",
			"filter":     "reserve transform filter [--after YYYY-MM-DD] [--before YYYY-MM-DD] [--min N] [--max N] [--drop-missing]",
		},
		map[string]any{
			"pct-change": "--period N",
			"diff":       "--order 1|2",
			"log":        "no command-specific flags",
			"index":      "--base 100 --at YYYY-MM-DD",
			"normalize":  "--method zscore|minmax",
			"resample":   "--freq monthly|quarterly|annual --method mean|last|sum",
			"filter":     "--after --before --min --max --drop-missing",
		},
		[]string{"JSONL observation rows", "table preview when output is a terminal"},
		[]string{
			"When you need to derive a new series stream from an existing one.",
			"When you want to filter, resample, normalize, or transform values before analysis or charting.",
		},
		[]string{
			"When you need rolling-window behavior; use `window roll` instead.",
			"When the source command is still in table mode rather than JSONL.",
		},
		[]string{
			"Convert raw levels to percent change or differences.",
			"Filter dates or resample monthly data to annual summaries.",
		},
		[]string{
			"reserve obs get CPIAUCSL --from cache --format jsonl | reserve transform pct-change --period 12",
			"reserve obs get GDP --from cache --format jsonl | reserve transform resample --freq annual --method mean",
		},
		[]string{
			"`transform` is not where rolling windows live. Use `reserve window roll` for that.",
			"Transforms auto-detect terminal output and may render a table; for downstream chaining, keep the output in JSONL form.",
		},
		[]string{"obs", "window", "analyze", "chart"},
	)
}

func buildVersionGuide() map[string]any {
	return makeGuide(
		"Report version, Go, and target-platform build metadata.",
		"`version` is for packaging, provenance, diagnostics, and audit trails.",
		"Use it to confirm what binary is running and to stamp outputs in CI or releases.",
		"Support command, not a JSONL pipeline stage.",
		"Writes build metadata in human-readable, JSON, or JSONL form.",
		map[string]any{
			"version": "reserve version [--format json|jsonl]",
		},
		map[string]any{
			"version": "primarily uses global `--format`",
		},
		[]string{"plain text build summary", "JSON object", "JSONL object"},
		[]string{
			"When you need to verify what binary version or target platform is running.",
			"When you want provenance metadata in CI, packaging, or audit logs.",
		},
		[]string{
			"When you want release notes or changelog narrative.",
			"When you want to inspect runtime config or cache state.",
		},
		[]string{
			"Check binary version before filing a bug report.",
			"Append build metadata to an audit stream.",
		},
		[]string{
			"reserve version",
			"reserve version --format jsonl >> audit.jsonl",
		},
		[]string{
			"`version` reports build facts only; it does not verify remote releases or update state.",
			"`build_time` depends on ldflags injection at build time and may be empty in ad hoc local builds.",
		},
		[]string{"onboard", "completion"},
	)
}

func buildWindowGuide() map[string]any {
	return makeGuide(
		"Compute rolling-window statistics from a JSONL observation stream.",
		"`window` is a dedicated pipeline family for rolling calculations and is intentionally separate from `transform`.",
		"Use it for moving averages, rolling standard deviations, and other windowed statistics over one series stream.",
		"Mid-pipeline stage: JSONL in, JSONL out.",
		"Reads JSONL observations from stdin and emits JSONL observations containing the rolling statistic.",
		map[string]any{
			"roll": "reserve window roll --stat mean|std|min|max|sum --window N [--min-periods M]",
		},
		map[string]any{
			"roll": "--stat mean|std|min|max|sum --window N --min-periods M",
		},
		[]string{"JSONL observation rows", "table preview when output is a terminal"},
		[]string{
			"When you need rolling means, rolling volatility, or other windowed metrics.",
			"When you want to smooth a series before trend analysis or charting.",
		},
		[]string{
			"When you need one-shot transforms like diff or resample rather than rolling windows.",
			"When you expect the command to live under `transform`.",
		},
		[]string{
			"Compute a 12-month moving average.",
			"Smooth YoY inflation before trend analysis.",
		},
		[]string{
			"reserve obs get UNRATE --from cache --format jsonl | reserve window roll --stat mean --window 12",
			"reserve obs get CPIAUCSL --start 2020-01-01 --format jsonl | reserve transform pct-change --period 12 | reserve window roll --stat mean --window 3",
		},
		[]string{
			"The command is `reserve window roll`, not `reserve transform roll`.",
			"NaN values are skipped in the rolling computation. If too few valid points remain, the output window is NaN.",
		},
		[]string{"obs", "transform", "analyze", "chart"},
	)
}
